public class AccountHelper {
    /*
    public static Boolean updateContactAddress(List<Contact> inputListContact){
        System.debug('AccountHelper inputListContact : '+inputListContact);
        List<Contact> updateContact = new List<Contact>();
        for(Contact con : inputListContact){
            con.Sample_Address__c = con.Account_Info__c;
            updateContact.add(con);
        }
        if(updateContact != null || !updateContact.isEmpty()){
            update inputListContact;
            return true;
        }else{
            return false;
        }
    }
    public static void temp(Account acclist){
        
         Contact test =  new  Contact (); 
        Contact a = [Select Id from Contact limit 1 ];
        system.debug(a);
        test.Sample_Address__c = a.name;
        insert test;
        system.debug('new account inserted with ID ' + test.id );
   
        
        
            
    }
    */

}